#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello world" | sudo tee /var/www/html/index.html
sudo sed -i '/server_name _/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
sudo service nginx restart
