#!/usr/bin/env bash
# ssh_config
Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    HostName 52.23.178.151
    User ubuntu
